### PR TITLE
webOS 3.x compat

### PR DESCRIPTION
**Pull request by Informatic**
This implements support for webOS 3.x in frontend part.

Amount of created/modified files is a side-effect of how enact treats "eject" operation - it copies over all build-related configuration files and scripts into local project. That is sadly required to modify anything in the way app is built.
If that is a problem, we could try using `webpack` directly, and effectively remove all `scripts/` directory.

This also removes dependency on webOS TV SDK by using `@webosose/ares-cli` tools from npm. (to be finished up)

### CODE REVIEW

**Comment by Informatic** [comment]
@Wouterdek this seems to be ready. Tested on Windows 10 

This doesn't support scroll events yet, from what I could tell, right? Also - it is expected that dpad center button presses are not transmitted as mouse down/up events?

**Comment by Wouterdek** [comment]
> @Wouterdek this seems to be ready. Tested on Windows 10

Great! I currently don't have access to my devices, but I can review this in 12 days.

> This doesn't support scroll events yet, from what I could tell, right? Also - it is expected that dpad center button presses are not transmitted as mouse down/up events?

I transmit whatever [I receive](https://github.com/Wouterdek/magic4pc/blob/master/webos/magic4pc/src/views/MainPanel.js#L166) from `keydown`/`keyup` events registered with `document.addEventListener`. There could be ways to receive more input types, but I didn't look into this much as I didn't need it myself.

**Comment by Informatic** [comment]
Sure. And I assume binding from colored keys to mouse buttons is done here?

https://github.com/Wouterdek/magic4pc/blob/5a8b1e4a5da41a848445fd5d71b445600376b73d/pc/magic4pc_win/magic4pc_win/MagicCursorDriver.cs#L103-L119

Middle remote button emits "enter" keycode, if I recall correctly - we could add support for that on windows service side. I'll verify this later, since I wanted to also write some minimal daemon for Linux.

**Comment by Wouterdek** [comment]
Tried the updated rootmy.tv today, and it worked! This is a lot more convenient than the developer mode app.
After messing around with node versions, I was able to compile this PR, and I don't see any regressions. I'll update the README with a bit more information on the compilation process.

Thanks!

**Pull request merged**
